package com.lhdb.game.dao;

import com.lhdb.game.entity.MGiveScoreLog;
import com.lhdb.game.entity.MGiveScoreLogExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


@Mapper
public interface MGiveScoreLogMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(MGiveScoreLog record);

    int insertSelective(MGiveScoreLog record);

    MGiveScoreLog selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(MGiveScoreLog record);

    int updateByPrimaryKey(MGiveScoreLog record);

    List<MGiveScoreLog> searchOnPage(MGiveScoreLog record);

    MGiveScoreLog count(MGiveScoreLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_give_score_log
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    int countByExample(MGiveScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_give_score_log
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    int deleteByExample(MGiveScoreLogExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_give_score_log
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    List<MGiveScoreLog> selectByExample(MGiveScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_give_score_log
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") MGiveScoreLog record, @Param("example") MGiveScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_give_score_log
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    int updateByExample(@Param("record") MGiveScoreLog record, @Param("example") MGiveScoreLogExample example);

}